In [13]:
import numpy as np

<h2> Unicode Test</h2>

In [14]:
string="안녕하세요 🤗(hello in Korean!)"

In [15]:
np.array([ord(char) for char in string])

array([ 50504,  45397,  54616,  49464,  50836,     32, 129303,     40,
          104,    101,    108,    108,    111,     32,    105,    110,
           32,     75,    111,    114,    101,     97,    110,     33,
           41])

In [16]:
np.array(list(string.encode('utf-8')))

array([236, 149, 136, 235, 133, 149, 237, 149, 152, 236, 132, 184, 236,
       154, 148,  32, 240, 159, 164, 151,  40, 104, 101, 108, 108, 111,
        32, 105, 110,  32,  75, 111, 114, 101,  97, 110,  33,  41])

In [17]:
np.array(list(string.encode('utf-16')))

array([255, 254,  72, 197,  85, 177,  88, 213,  56, 193, 148, 198,  32,
         0,  62, 216,  23, 221,  40,   0, 104,   0, 101,   0, 108,   0,
       108,   0, 111,   0,  32,   0, 105,   0, 110,   0,  32,   0,  75,
         0, 111,   0, 114,   0, 101,   0,  97,   0, 110,   0,  33,   0,
        41,   0])

<h2> BPE </h2>

In [18]:
with open("./TextforTest.txt","r") as f:
    text=f.read()

In [19]:
from Utils import text2idx
tokens=text2idx(text)
print(tokens)

[85, 110, 105, 99, 111, 100, 101, 33, 32, 85, 78, 73, 67, 79, 68, 69, 63, 32, 85, 78, 73, 67, 79, 68, 69, 33, 32, 240, 159, 152, 138, 32, 84, 104, 101, 32, 118, 101, 114, 121, 32, 110, 97, 109, 101, 32, 115, 116, 114, 105, 107, 101, 115, 32, 102, 101, 97, 114, 32, 97, 110, 100, 32, 97, 119, 101, 32, 105, 110, 116, 111, 32, 116, 104, 101, 32, 104, 101, 97, 114, 116, 115, 32, 111, 102, 32, 112, 114, 111, 103, 114, 97, 109, 109, 101, 114, 115, 32, 119, 111, 114, 108, 100, 119, 105, 100, 101, 46, 32, 87, 101, 32, 97, 108, 108, 32, 107, 110, 111, 119, 32, 119, 101, 32, 111, 117, 103, 104, 116, 32, 116, 111, 32, 226, 128, 156, 115, 117, 112, 112, 111, 114, 116, 32, 85, 110, 105, 99, 111, 100, 101, 226, 128, 157, 32, 105, 110, 32, 111, 117, 114, 32, 115, 111, 102, 116, 119, 97, 114, 101, 32, 40, 119, 104, 97, 116, 101, 118, 101, 114, 32, 116, 104, 97, 116, 32, 109, 101, 97, 110, 115, 226, 128, 148, 108, 105, 107, 101, 32, 117, 115, 105, 110, 103, 32, 119, 99, 104, 97, 114, 95, 116, 32, 102, 1

In [20]:
from Utils import stat_dict
stats_instance=stat_dict(tokens)
print(stats_instance.counts)

{(85, 110): 5, (110, 105): 5, (105, 99): 5, (99, 111): 5, (111, 100): 5, (100, 101): 6, (101, 33): 1, (33, 32): 2, (32, 85): 6, (85, 78): 2, (78, 73): 2, (73, 67): 2, (67, 79): 2, (79, 68): 2, (68, 69): 2, (69, 63): 1, (63, 32): 1, (69, 33): 1, (32, 240): 1, (240, 159): 1, (159, 152): 1, (152, 138): 1, (138, 32): 1, (32, 84): 1, (84, 104): 1, (104, 101): 5, (101, 32): 19, (32, 118): 1, (118, 101): 3, (101, 114): 6, (114, 121): 2, (121, 32): 2, (32, 110): 2, (110, 97): 1, (97, 109): 4, (109, 101): 6, (32, 115): 5, (115, 116): 5, (116, 114): 3, (114, 105): 4, (105, 107): 2, (107, 101): 2, (101, 115): 3, (115, 32): 10, (32, 102): 4, (102, 101): 1, (101, 97): 4, (97, 114): 7, (114, 32): 6, (32, 97): 10, (97, 110): 10, (110, 100): 6, (100, 32): 4, (97, 119): 1, (119, 101): 2, (32, 105): 6, (105, 110): 12, (110, 116): 4, (116, 111): 3, (111, 32): 3, (32, 116): 8, (116, 104): 7, (32, 104): 1, (114, 116): 3, (116, 115): 3, (32, 111): 4, (111, 102): 3, (102, 32): 2, (32, 112): 3, (112, 114): 2,

In [21]:
print(stats_instance.return_sorted_dict())

[(19, (101, 32)), (12, (105, 110)), (10, (115, 32)), (10, (97, 110)), (10, (32, 97)), (8, (32, 116)), (7, (116, 104)), (7, (97, 114)), (6, (116, 32)), (6, (114, 32)), (6, (111, 114)), (6, (110, 103)), (6, (110, 100)), (6, (109, 101)), (6, (101, 114)), (6, (100, 101)), (6, (32, 105)), (6, (32, 85)), (5, (226, 128)), (5, (117, 115)), (5, (115, 116)), (5, (111, 100)), (5, (110, 105)), (5, (110, 32)), (5, (105, 99)), (5, (104, 101)), (5, (99, 111)), (5, (85, 110)), (5, (44, 32)), (5, (32, 115)), (4, (116, 105)), (4, (116, 101)), (4, (115, 44)), (4, (114, 105)), (4, (111, 117)), (4, (110, 116)), (4, (104, 97)), (4, (103, 32)), (4, (101, 97)), (4, (100, 32)), (4, (97, 109)), (4, (32, 119)), (4, (32, 111)), (4, (32, 102)), (3, (118, 101)), (3, (116, 115)), (3, (116, 114)), (3, (116, 111)), (3, (114, 116)), (3, (114, 115)), (3, (114, 101)), (3, (111, 102)), (3, (111, 32)), (3, (108, 108)), (3, (108, 101)), (3, (108, 32)), (3, (101, 115)), (3, (101, 110)), (3, (97, 116)), (3, (46, 32)), (3, (32

In [22]:
print(stats_instance.return_top_pair())

(101, 32)


test for merge function

In [23]:
from Utils import merge
test_text="aaabdaaabac"
tokens=text2idx(test_text)
print(tokens)

[97, 97, 97, 98, 100, 97, 97, 97, 98, 97, 99]


In [24]:
merge(tokens,(97,97),256)

[256, 97, 98, 100, 256, 97, 98, 97, 99]

BPE